# configuration for netlify cms

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

media_folder: static/assets
public_folder: static

display_url: https://jamstack-static-generated-app.netlify.com

show_preview_links: true


collections:

  # The product categories are matched with
  - name: productCategories
    label: Product Categories
    editor:
      preview: true
    folder: content/productCategories
    slug: '{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: Slug, name: slug, widget: string }
      - { label: Name, name: name, widget: string }
      - { label: Featured Image, name: featuredImage, widget: image, required: false }
      - { label: Body, name: body, widget: markdown }

  # Static pages
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/pages/home.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

  # Add global settings here
  - name: 'settings'
    label: 'Settings'
    delete: false
    editor:
      preview: false
    files:
      - file: 'settings/siteMetadata.json'
        label: 'Site Metadata'
        name: 'siteMetadata'
        fields:
          # All fields should be multilingual, a special widget is needed here
          - label: "Site Title"
            name: "title"
            widget: "object"
            fields:
              - { label: "Deutsch", name: "de", widget: "string" }
              - { label: "English", name: "en", widget: "string" }
          - {
              label: Site Url,
              name: siteUrl,
              widget: string
            }
          - {
              label: Site Description,
              name: description,
              widget: text,
            }
          - {
              label: Site Creator,
              name: siteCreator,
              widget: text,
            }
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - { label: Image, name: image, widget: image, required: false }
          - {
              label: Google Analytics Tracking Id,
              name: googleTrackingId,
              widget: string,
              required: false,
            }
